### ISSUE TITLE
Can't compile any branch

### ISSUE THREAD

**Issue by cerk** [xTrayambak/ferus#18]
Hello,

I wanted to try out ferus and tried `nimble install` on every single branch in the repo. The two errors I commonly encountered were:

```
Error:  Unable to identify url: https://github.com/xTrayambak/ferus_sanchar
```

and 

```
ferus/nim.cfg(20, 1) Error: unknown hint: LineTooLong
```

I'm probably doing something dumb (I'm on nim v 2.0.2 currently). Thanks for attempting ferus!

**Comment by xTrayambak** [comment]
I've actually taken a tiny break from ferus until June of this year. I have no intent to fix it until my summer break starts during that time. If you look at the contribution graphs, my most productive months were the ones in which I was free from my studies, haha. Since then, I've just been contributing to Nim/Nimble a little bit. A lot has changed in the meanwhile --

1) Chame (the HTML parser we use) has released a new version which means Ferus won't work
2) ferus_sanchar is now just sanchar, and hence the repo URL has been changed.
3) Ferus crashes when using ORC

I'll have to bring the codebase back to pace sometime soon. I'm currently working on [stylus](https://github.com/ferus-web/stylus), a CSS3 parser and tokenizer. I've just not had the energy to fix everything up, but I'll try to do it since I'm free for the next few days :)

**Comment by xTrayambak** [comment]
Another thing I want to do is move away from chronicles since it isn't really meant to be used for a real-time app like Ferus, and a more minimal logger is enough.

**Comment by xTrayambak** [comment]
Can you please try out the `catching-up` branch now?

**Comment by xTrayambak** [comment]
Ferus now works with ORC on Nim 2 with Chame's latest version. I'll be merging `catching-up` with `main`.

**Comment by cerk** [comment]
That was quick - thank you! Compiles fine now with the `catching-up` branch.

**Comment by xTrayambak** [comment]
I've merged it into `main` already, so that should work too. The migration to Chame's newest API is a flex-tape fix though, and I'll need to improve it later.
